-- What she accepted, and what we then sent her to.
--
-- The cashier's first rule is that it refuses unless a STORED proposal row for
-- this conversation carries decision = 'accept', decided recently. The model
-- passes a proposal id and never an itinerary, for the same reason it passes
-- source ids and never prices (lesson 4.4): a hand-off built from what the
-- model sent is a hand-off to whatever the model decided to send.
--
-- Deliberately the minimum the cashier's precondition needs. main's version of
-- this table also carries a rehydrated itinerary, a requirements snapshot, a
-- gate outcome, review rounds and accepted totals; every one of those belongs
-- to a consumer this branch does not have yet (proposal cards are lesson 5.7,
-- the reviewer seat is module 5, the eval replay is module 6). A column added
-- for a reader that does not exist is a column nobody keeps correct.
create table course.proposals (
  id              uuid primary key default gen_random_uuid(),
  seq             bigint generated always as identity,
  conversation_id uuid not null,
  user_id         uuid not null,
  turn_id         uuid references course.turns(id) on delete set null,
  -- The references the gates approved, exactly as ProposalRefsSchema validated
  -- them: {sourceId, quantity, slot}. Never a price and never a total, because
  -- the cashier re-reads every price out of course.tool_results and re-quotes
  -- it before anything is emitted.
  refs            jsonb not null,
  decision        text check (decision in ('accept','reject')),
  decided_at      timestamptz,
  created_at      timestamptz not null default now(),
  foreign key (conversation_id, user_id) references course.conversations (id, user_id) on delete cascade,
  -- A decision with no timestamp cannot be aged, and the cashier's rule is that
  -- an acceptance goes stale after thirty minutes. A timestamp with no decision
  -- is a row claiming she answered without saying what she answered. Neither is
  -- a state anything should have to interpret.
  constraint proposals_decision_has_a_time check ((decision is null) = (decided_at is null)),
  -- The cashier reads (id, conversation_id). A bare id lookup would let one
  -- conversation's proposal be handed off from another conversation's turn.
  unique (id, conversation_id)
);
create index proposals_by_conversation on course.proposals (conversation_id, seq desc);
create index proposals_by_turn on course.proposals (turn_id) where turn_id is not null;

-- Every booking link we emitted, minted BEFORE the link exists.
--
-- The id is generated by the caller and is not defaulted here, which is the
-- whole mechanism: the cashier mints the uuid, embeds it in the URL as the
-- affiliate sub-id, and inserts the row carrying the exact URL it emitted. A
-- database-generated id would mean writing the row, reading it back, and
-- building the URL afterwards, so a crash between the two would leave a row
-- claiming a link that was never built.
create table course.link_clicks (
  id           uuid primary key,
  seq          bigint generated always as identity,
  proposal_id  uuid not null references course.proposals(id) on delete cascade,
  turn_id      uuid references course.turns(id) on delete set null,
  user_id      uuid not null,
  item_id      text not null,
  supplier     text not null,
  -- The exact string she was given, not a template and not the pieces. A URL
  -- rebuilt later from its parts is a different URL the day a template changes.
  url          text not null,
  -- The sub-id inside that URL, and the join key module 7's conversions land
  -- on. Unique, because a conversion reported against a ref we cannot resolve
  -- to one click is a conversion nobody can attribute.
  tracking_ref text not null unique,
  -- The price we told her, at the moment we told her, in the supplier's
  -- currency and minor units. Module 7 compares a reported booking amount
  -- against this. It is the number that cannot be added later: a click already
  -- happened, and what it was quoted at is not recoverable from anywhere else.
  quoted_minor bigint not null check (quoted_minor >= 0),
  currency     char(3) not null,
  -- Whether the price above was re-quoted against a supplier that says it can
  -- re-quote, or merely disclosed with its age. Stored rather than derived,
  -- because the message she was shown depends on it and a worker that dies
  -- after emitting has to be able to say the same sentence again
  -- (src/worker.ts's point-of-no-return branch).
  verified     boolean not null,
  -- When the price above was quoted, which is the age the hand-off message
  -- states when it could not be re-checked. Stored for the same reason
  -- `verified` is: a worker that dies after emitting has to be able to say the
  -- SAME sentence again (src/worker.ts's point-of-no-return branch), and an age
  -- recomputed at recovery time would read "just now" about a price quoted
  -- hours ago. Deliberately NO default: `default now()` would produce exactly
  -- that untrue sentence silently, and this is a property of the supplier's
  -- quote rather than of this insert.
  quoted_at    timestamptz not null,
  rendered_at  timestamptz not null default now(),
  clicked_at   timestamptz,
  -- One link per item per proposal. A second hand-off of the same proposal is a
  -- duplicate, not a second offer, and this makes the second write impossible
  -- rather than idempotent: it is the last line of defence, not the mechanism.
  -- What answers the model is the cashier, which reads this table for the
  -- proposal and refuses before it re-quotes anything (src/cashier.ts, and
  -- emittedForProposal in src/repo/linkClicks.ts), so reaching this constraint
  -- means something has gone around that refusal and the caller gets a Postgres
  -- error rather than an answer.
  unique (proposal_id, item_id)
);
create index link_clicks_by_turn on course.link_clicks (turn_id) where turn_id is not null;

-- 0012 created gate_results.proposal_id with no foreign key, because its parent
-- table did not exist yet. It does now.
alter table course.gate_results
  add constraint gate_results_proposal_id_fkey
    foreign key (proposal_id) references course.proposals(id) on delete set null;
create index gate_results_by_proposal on course.gate_results (proposal_id) where proposal_id is not null;

-- Found by the catalogue-wide audit in test/schema-corpus.test.ts, and older
-- than this migration: 0002 gave course.model_calls a foreign key to
-- course.turns and no index leading on the child column, so deleting a turn
-- scans every model call ever recorded. The audit is written against the
-- catalogue rather than against a list of tables precisely so that a defect
-- nobody thought to look for lands in the first migration after it is found,
-- which is this one. Partial, like messages_by_turn (0008) and
-- gate_results_by_turn (0012), because the column is nullable.
create index model_calls_by_turn on course.model_calls (turn_id) where turn_id is not null;
